checkout/urls.py
from django.urls import path
from . views import checkout, payment, charge, orderView

app_name = "checkout"

urlpatterns = [
	path('checkout/', checkout, name="index"),
	path('payment/', payment, name="payment"),
	path('charge/', charge, name="charge"),
	path('my-orders/', orderView, name="orderView")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from products import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('products.urls', namespace='mainapp')),
    path('', include('checkout.urls', namespace='checkout')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
from products import views
from . views import ProductDetail
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart
app_name= 'mainapp'



urlpatterns = [
    path('', views.featured_list, name='home'),
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
    path('product/<slug>/', ProductDetail.as_view(), name='product'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),

]

products/models.py
from django.db import models

#Category Model
class Category(models.Model):
    title = models.CharField(max_length=300)
    primaryCategory = models.BooleanField(default=False)

    def __str__(self):
        return self.title


# Product Model
class Product(models.Model):
    mainimage = models.ImageField(upload_to='products/', blank=True)
    name = models.CharField(max_length=300)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Detail Text')
    price = models.FloatField()
    featured_row_1 = models.BooleanField(default=False)
    featured_row_2 = models.BooleanField(default=False)
    featured_row_3 = models.BooleanField(default=False)

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from products.models import Product
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.forms import ModelForm
from django.contrib.auth.mixins import LoginRequiredMixin

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['mainimage', 'name', 'slug', 'category', 'preview_text', 'detail_text', 'price']

class ProductDetail(LoginRequiredMixin, DetailView):
	model = Product


def featured_list(request, template_name='products/home.html'):
    product = Product.objects.all()
    data = {}
    data['object_list'] = product
    return render(request, template_name, data)

def product_list(self):
    product = Product.objects.order_by('-id')[0:10]
    data = {}
    data['object_list'] = product
    return render(request, template_name, data)

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>Collywobbles</title>
  <style>
  	.card{
  		    height: 350px;
  	}
  	.card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden; }
  .card-product .price-new, .card-product .price {
    margin-right: 5px; }
  .card-product .price-old {
    color: #999; }
  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center; }
    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover; }

      .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px; }
  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .title {
    margin-top: 0; }
  </style>
</head>
<body>
{% include 'products/navbar.html' %}

    {% if messages %}
    <div class="messages container mt-2">
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        </div>
        {% endfor %}
    </div>
  {% endif %}
{% block content %}
{% endblock %}
<!--- Footer -->
<footer>
<div id="footer" class="container-fluid padding">
    <div class="row text-center">
        <div class="col-md-4">
            <hr class="light">
            <h5>Contact Us</h5>
            <hr class="light">
            <p>(303) 905-4102</p>
            <p>tatewilson4@gmail.com</p>
            <p>100 Blah Street</p>
            <p>Denver, CO, 80234</p>
        </div>
        <div class="col-md-4">
            <hr class="light">
            <h5>Our hours</h5>
            <hr class="light">
            <p>Monday: 9AM-5PM</p>
            <p>Saturday: 11AM-4PM</p>
            <p>Sunday: 11AM-4PM</p>
        </div>
        <div class="col footer_text">
                <hr class="light">
                <h5>Social Media</h5>
                <hr class="light">
                <p><a href="#"><img src="../../../static/img/Github.png" class="icon_img"></a></p>
                <p><a href="#"><img src="../../../static/img/Linkedin.png" class="icon_img"></a></p>
                <p><a href="#"><img src="../../../static/img/google-plus-icon.png" class="icon_img"></a></p>
            </div>
        <div class="col-12">
            <hr class="light-100">
            <h5>&copy; collywobbles.com</h5>
        </div>
    </div>
</div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script>

</script>
</body>
</html>

products/templates/products/home.html
{% extends 'products/base.html' %}
{% block content %}

<img src="../../static/img/NUMI.jpg" style="width:100%; height: 550px;object-fit:cover;overflow:hidden;">
<div class="addvertisment container-fluid">
    <ul class="smooth-scroll list-unstyled">
        <li>
            <h5 class="down_arrow"><a href="#scroll_to_featured">^</a></h5>
        </li>
    </ul>
</div>
<header>
    <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
      <source src="../../static/img/white-satin.mp4" type="video/mp4">
    </video>
</header>

<div class="container-fluid home_div">

    <div id="scroll_to_featured" class="row">
        {% for product in object_list %}
        {% if product.featured_row_1 == True %}
        <div class="row1 col-md-6 col-sm-12 col-lg-3 img-hover-zoom">
            <a href="product/{{ product.slug }}"><img class="row1 img-responsive" src="media/{{ product.mainimage }}" style="width: 100%; height: 300px;"></a>
        </div> <!-- col // -->
        {% endif %}
        {% endfor %}
    </div>
    <div class="row">
        {% for product in object_list %}
        {% if product.featured_row_2 == True %}
        <div class="row2 col-sm-12 col-lg-6 img-hover-zoom">
            <a href="product/{{ product.slug }}"><img class="row2 img-responsive" src="media/{{ product.mainimage }}" style="width: 100%; height: 300px;"></a>
        </div> <!-- col // -->
        {% endif %}
        {% endfor %}
    </div>
    <div class="row">
        {% for product in object_list %}
        {% if product.featured_row_3 == True %}
        <div class="row3 col-xs-12 col-sm-4 img-hover-zoom">
            <a href="product/{{ product.slug }}"><img class="row3 img-responsive" src="media/{{ product.mainimage }}" style="width: 100%; height: 300px;"></a>
        </div> <!-- col // -->
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

products/templates/products/navbar.html
{% load cart_tag %}
<title>Colywobbles</title>
<nav class="navbar-large fixed-top navbar-expand-lg navbar-light">
    <div class="nav-contain container-fluid">
        <div class="container d-flex justify-content-between navbar-small-contain">
            <a id="nav-brand-small" class="navbar-toggler font-weight-bold navbar-small" href="/">clly</a>
            <div class="username-or-login-small col-4 navbar-toggler">
                {% if request.user.is_authenticated %}

                <li class="nav-item dropdown auth-dropdown" style="text-align:center;">
                    <a class="login-logout nav-link dropdown-toggle" href="{% url 'mainapp:cart-home' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user-tie"></i> {{ request.user.username }}
                    </a>
                    <div class="dropdown-menu nav-dropdown-item" aria-labelledby="navbarDropdown">
                        <a class="login-logout dropdown-item" href="#">Dashboard</a>
                        <a class="login-logout dropdown-item" href="{% url 'checkout:orderView' %}">Orders</a>
                        <div class="dropdown-divider"></div>
                        <a class="login-logout dropdown-item" href="/accounts/logout/">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a  class="login-logout btn btn-primary" href="/accounts/login/">Login / Register</a>
                </li>
                {% endif %}
            </div>
            <div id="hamburger-small" class="dropdown navbar-toggler">
                <button id="hamburger-small" class="btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span id="hamburger-small" class="navbar-toggler-icon"></span>
                </button>
                <div id="hamburger-small" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a id="hamburger-dropdown"class="dropdown-item" href="#">Men</a>
                    <a id="hamburger-dropdown" class="dropdown-item" href="#">Women</a>
                    <a id="hamburger-dropdown" class="dropdown-item" href="#">Accessories</a>
                    <a id="hamburger-dropdown" class="dropdown-item" href="#">Electronics</a>
                </div>
            </div>
        </div>

        <div class="row collapse navbar-collapse">
            <div class="logo-nav col" style="text-align:right">
                <a class="navbar-brand font-weight-bold" href="/">clly</a>
            </div>
            <div class="middle-nav col-8" style="text-align:center;vertical-align:middle;">
                <form class="form-inline" action="/action_page.php">
                    <input id="search-bar" class="form-control mr-sm-2" type="text" placeholder="     Search" style="width:100%">
                </form>
                <div class="bottom-middle-nav row">
                    <div class="col-2 men-nav">
                        <li {% if request.path == 'contact' %}class="nav-item active"{% else %}class="nav-item"{% endif %}>
                            <a class="nav-link" href="#">Men<span class="sr-only">(current)</span></a>
                        </li>
                    </div>
                    <div class="women-nav col-2">
                        <li class="nav-item">
                            <a class="women-lsit nav-link" href="#">Women</a>
                        </li>
                    </div>
                    <div class="username-or-login col-4">
                        {% if request.user.is_authenticated %}

                        <li class="nav-item dropdown auth-dropdown" style="text-align:center;">
                            <a class="login-logout nav-link dropdown-toggle" href="{% url 'mainapp:cart-home' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-user-tie"></i> {{ request.user.username }}
                            </a>
                            <div class="dropdown-menu nav-dropdown-item" aria-labelledby="navbarDropdown">
                                <a class="login-logout dropdown-item" href="#">Dashboard</a>
                                <a class="login-logout dropdown-item" href="{% url 'checkout:orderView' %}">Orders</a>
                                <div class="dropdown-divider"></div>
                                <a class="login-logout dropdown-item" href="/accounts/logout/">Logout</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a  class="login-logout btn btn-primary" href="/accounts/login/">Login / Register</a>
                        </li>
                        {% endif %}
                    </div>
                    <div class="access-nav col-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Accessories</a>
                        </li>
                    </div>
                    <div class="elec-nav col-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Electronics</a>
                        </li>
                    </div>
                </div>
            </div>
            <div class="cart-div col" style="text-align:center;">
                <a id="cart" class="nav-link" href="{% url 'mainapp:cart-home' %}">
                    <i class="fa fa-shopping-cart"></i> Cart
                </a>
            </div>
        </div>
    </div>

</nav>

products/templates/products/product_detail.html
{% extends 'products/base.html' %}


{% block content %}
<div class="push"></div>
<div class="container my-5">
	<div class="row">
		<div class="col-lg-6 col-md-12">
			<div class="col-sm-5 border-right">
				<article>
					<div>
						<div><a href="#"><img class="product-detail-img" src="/media/{{ object.mainimage }}" style="width: 450px;"></a></div>
					</div> <!-- slider-product.// -->
				</article> <!-- gallery-wrap .end// -->
			</div>
		</div>
		<div class="col-lg-6 col-md-12">
			<article class="card-body p-5">
				<h3 class="title mb-3">{{ object.name }}</h3>
				<p class="price-detail-wrap">
					<span class="price h3 text-warning">
						<span class="currency">US $</span><span class="num">{{ object.price }}</span>
					</span>

				</p> <!-- price-detail-wrap .// -->
				<dl class="item-property">
					<dt>Description</dt>
					<dd><p>{{ object.preview_text }}</p></dd>
				</dl>

				<a href="{% url 'mainapp:cart' object.slug %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to cart </a>
			</article> <!-- card-body.// -->
		</div>
	</div>
</div>

</div>
<!--container.//-->
<div class="push"></div>
{% endblock %}